nome = str(input('Digite seu nome completo: ')).strip()
nome1 = nome.split()
print(f'Maiúsculo: {nome.upper()}')
print(f'Minúsculo: {nome.lower()}')
print(f'Qntd de Letras: {len(nome) - nome.count(" ")}')
print(f'Qntd de Letras 1º nome: {len(nome1[0])}')
